### ISSUE TITLE
What am I doing not right ?

### ISSUE THREAD

**Issue by PGDataHome** [dundalek/liz#1]
Hi,

I was giving a try at liz, installed it, and tried it.

And even with the hello-world, II can't make it run
Here's the hello.zig file generated
<----
const print = @import("std").debug.print;
fn main() void {
    print("Hello, world!\n", .{});
}
--->
as we can remark the fn  main lacks the pub key, thus making it private and doesnt compile

**Comment by PGDataHome** [comment]
Contrary to what is displayed on your github readme (https://github.com/dundalek/liz#readme)

**Comment by dundalek** [comment]
Hi, sorry about that, I made some changes to `defn` and `defn-` to behave more like Clojure which were not released yet. It should now work with the [latest release](https://github.com/dundalek/liz/releases/tag/v0.1.1).
